version: '3.1'

services:
  postgres:
    image: postgres
    container_name: postgres
    ports:
    - "5432:5432"
    networks:
    - quantum-network

networks:
  quantum-network:
    driver: bridge

